import fitness from "../../Assets/img/fitness.png";
import amala from "../../Assets/img/amala.png";
import ai from "../../Assets/img/gener8.png";
// import mov from "../../Assets/img/movieApp.png";
// import cocktail from "../../Assets/img/cocktaily.png";

export const ProjectsData = [
  {
    id: 1,
    feats: [
      "Display X number of amala spots by default",
      "Get User Location using Geolocation API",
      "Display spots closest to the user's location",
      "Show more details about a spot when clicked",
    ],
    name: "Everything Amala",
    det: "This is A React-Based Web Application to find Amala Restaurants all over the world. It uses the Google Places API to fetch the restaurants and the Google Maps API to display the location of the restaurants. React, SCSS, Google Places API, Google Maps API",
    code: "https://github.com/mo-renike/everything-amala",
    live: "https://everything-amala.vercel.app/",
    image: amala,
    stack: ["React", "Scss", "Google Places API"],
  },
  {
    id: 2,
    feats: ["Search for excercises according to bodypart", "Show more details about an excercise when clicked", "Watch Youtube videos on how to do the excercise"],
    name: "Fitness App",
    det: "A React based app that displays gym execrises with corresponding gifs and a details page. React, SCSS, WebAPIs",
    code: "https://github.com/mo-renike/fitness",
    live: "https://fitnessexercises.netlify.app",
    image: fitness,
    stack: ["React", "Scss", "WebAPIs"],
  },
  {
    id: 3,
    feats: [
      "Generate an image based on a prompt",
      "Share generated image",
      "View all the images generated by different users",
    ],
    name: "Ai image generator",
    det: "A React based app that generates images using the OpenAI API.",
    live: "https://ai-image-generator-alpha.vercel.app/",
    code: "https://github.com/mo-renike/Ai_image_generator",
    image: ai,
    stack: ["React", "Tailwind", "OpenAI API", "GPT-3", "Firebase", "Cloudinary"],
  },

  // {
  //   id: 3,
  //feats: "",
  //   name: "Edutech Website",
  //   det: "Implementation of a figma website design using HTML, Sass and Vanilla Javascript",
  //   code: "https://github.com/mo-renike/edutech",
  //   live: "https://mo-renike.github.io/edutech/",
  //   img: edutech,
  // },
  // {
  //   id: 5,
  //   name: "Movies Review App",
  //   det: "A Javacsript based app that displays movies with corresponding image and a details preview using HTML5, CSS3, Vanilla Javascript, WebAPIs",
  //   code: "https://github.com/mo-renike/Movie-App",
  //   live: "https://mo-renike.github.io/Movie-App/",
  //   img: mov,
  // },
  // {
  //   id: 5,
  //   name: "Cocktail App",
  //   det: "A Javacsript based app that displays cocktails with corresponding image and a details page using HTML5, CSS3, Vanilla Javascript, WebAPIs",
  //   code: "https://github.com/mo-renike/cocktail-app",
  //   live: "https://cocktaily1.netlify.app/",
  //   img: cocktail,
  // },
  // {
  //   id: 4,
  //   name: "50 Javascript Projects",
  //   det: "A collection of 50 projects in 50 days using pure HTML, CSS and Javascript",
  //   code: "https://github.com/mo-renike/50Javascript-projects",
  //   live: "https://mo-renike.github.io/50Javascript-projects/",
  //   img: proj,
  // },
];
